# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeviceControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeviceControl
	pod 'Alamofire', '~> 4.7'
	pod 'CocoaMQTT', '1.0.18'
  target 'DeviceControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeviceControlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
